export const actionTypes = {
    SET_PRODUCTS:  "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SET_OTP: 'SET_OTP',
}

